# ABOUTME: Protobuf::Class::Codegen — the AOT renderer behind bin/protobuf-gen-perl:
# maps protobuf packages to Perl namespaces and emits one deterministic .pm per .proto (§4.12).
use v5.38;
use warnings;

package Protobuf::Class::Codegen;

use Protobuf::Schema::Serializer ();

# package_for($proto_package, $prefix) -> Perl namespace.
#
# Every protobuf path component is PascalCased. When $prefix is given (e.g.
# 'T::Api'), it REPLACES that many leading components of the proto package, so
# protobuf temporal.api.common.v1 under prefix T::Api becomes T::Api::Common::V1.
# An empty proto package maps to the bare prefix (or to '' when none given).
sub package_for ( $proto_package, $prefix = undef ) {
    my @components =
        map { _pascal_case($_) } grep { length } split /\./, $proto_package;

    if ( defined $prefix && length $prefix ) {
        my @prefix_parts = split /::/, $prefix;
        # The prefix stands in for its own depth of leading proto components.
        my $depth = scalar @prefix_parts;
        @components = @components[ $depth .. $#components ];
        @components = () if !@components || !defined $components[0];
        return join '::', @prefix_parts, @components;
    }

    return join '::', @components;
}

# perl_class_for($message_full_name, $proto_package, $prefix) -> Perl class.
#
# A message's full_name is its proto package plus its (possibly dotted, for
# nested messages) name. The package portion maps via package_for; the message
# path components are appended PascalCase-untouched (proto message names are
# already PascalCase by convention, and protoc preserves them verbatim).
sub perl_class_for ( $message_full_name, $proto_package, $prefix = undef ) {
    my $base = package_for( $proto_package, $prefix );

    my $local = $message_full_name;
    if ( length $proto_package ) {
        $local =~ s/^\Q$proto_package\E\.//;
    }
    my @parts = split /\./, $local;

    return join '::', ( length $base ? ($base) : () ), @parts;
}

# Convert one protobuf path component (snake_case or lower) to PascalCase:
# split on underscores, uppercase each piece's first letter. 'common' -> 'Common',
# 'v1' -> 'V1', 'foo_bar' -> 'FooBar'.
sub _pascal_case ($component) {
    return join '', map { ucfirst } split /_/, $component;
}

# output_path($file, $prefix) -> the .pm path RELATIVE to the output dir.
#
# Derived from the .proto FILE path (not the proto package): each path component
# is PascalCased and the prefix replaces the leading components, exactly as
# package_for does, with the final '.proto' becoming '.pm'. So
# temporal/api/common/v1/message.proto under prefix T::Api -> T/Api/Common/V1/Message.pm.
sub output_path ( $file, $prefix = undef ) {
    my $rel = $file->name;
    $rel =~ s{\.proto$}{};
    ( my $dotted = $rel ) =~ s{/}{.}g;
    my $pkg = package_for( $dotted, $prefix );
    ( my $path = $pkg ) =~ s{::}{/}g;
    return "$path.pm";
}

# loader_package($file, $prefix) -> the Perl package name the emitted file
# declares. Mirrors output_path's mapping joined with '::'.
sub loader_package ( $file, $prefix = undef ) {
    my $rel = $file->name;
    $rel =~ s{\.proto$}{};
    ( my $dotted = $rel ) =~ s{/}{.}g;
    return package_for( $dotted, $prefix );
}

# render_file($schema, $file, $prefix) -> the .pm source text.
#
# Emits a single module that, at load time, reconstructs the file's
# Schema::Message tree as static Perl (NO parser dependency) and installs each
# message class via Protobuf::Class::Generator — the SAME runtime build path, so
# the accessor/codec contract cannot drift from the runtime-generated classes.
# Deterministic: messages and their fields are emitted in a stable sorted order.
sub render_file ( $schema, $file, $prefix = undef ) {
    my $loader      = loader_package( $file, $prefix );
    my $proto_pkg   = $file->package;
    my @messages    = _all_messages_in_file($file);

    # Stable order: by full_name, so regeneration is byte-identical regardless
    # of the parser's internal ordering.
    @messages = sort { $a->full_name cmp $b->full_name } @messages;

    my @class_for =
        map { [ $_, perl_class_for( $_->full_name, $proto_pkg, $prefix ) ] }
        @messages;

    my @out;
    push @out, "# ABOUTME: Generated by protobuf-gen-perl from " . $file->name . ".";
    push @out, "# Do not edit by hand; regenerate from the .proto source.";
    push @out, "use v5.38;";
    push @out, "use warnings;";
    push @out, "";
    push @out, "package $loader;";
    push @out, "";
    push @out, "use Protobuf::Schema;";
    push @out, "use Protobuf::Schema::File;";
    push @out, "use Protobuf::Schema::Message;";
    push @out, "use Protobuf::Schema::Field;";
    push @out, "use Protobuf::Schema::Oneof;";
    push @out, "use Protobuf::Class::Generator ();";
    push @out, "";
    push @out, "# The file's schema, reconstructed statically (no parser at runtime).";
    push @out, "my \$file = " . Protobuf::Schema::Serializer::render_file($file) . ";";
    push @out, "my \$schema = Protobuf::Schema->new;";
    push @out, "\$schema->add_file(\$file);";
    push @out, "\$schema->resolve;";
    push @out, "";
    push @out, "# Install one class per message via the shared runtime build path.";
    for my $pair (@class_for) {
        my ( $message, $target ) = @$pair;
        my $fq = _perl_string( $message->full_name );
        push @out, "Protobuf::Class::Generator->build(";
        push @out, "    schema         => \$schema,";
        push @out, "    message        => \$schema->message($fq),";
        push @out, "    target_package => '$target',";
        push @out, ");";
    }
    push @out, "";
    push @out, "1;";
    push @out, "";

    return join( "\n", @out );
}

# Every message defined in $file, including nested messages (recursively).
sub _all_messages_in_file ($file) {
    my @all;
    my @stack = @{ $file->messages };
    while ( my $m = shift @stack ) {
        push @all, $m;
        push @stack, @{ $m->nested_messages };
    }
    return @all;
}

# Render a Perl single-quoted string literal for $value (escaping ' and \).
sub _perl_string ($value) {
    $value //= '';
    $value =~ s/([\\'])/\\$1/g;
    return "'$value'";
}

1;

__END__

=encoding utf-8

=head1 NAME

Protobuf::Class::Codegen - AOT renderer for proto3 message classes

=head1 SYNOPSIS

    use Protobuf::Class::Codegen;

    my $pkg  = Protobuf::Class::Codegen::package_for('temporal.api.common.v1', 'T::Api');
    # 'T::Api::Common::V1'

    my $src  = Protobuf::Class::Codegen::render_file($schema, $file, 'T::Api');
    my $path = Protobuf::Class::Codegen::output_path($file, 'T::Api');
    # 'T/Api/Common/V1/Message.pm'

=head1 DESCRIPTION

The rendering engine behind C<bin/protobuf-gen-perl>. It maps
protobuf packages to Perl namespaces and emits one C<.pm> per C<.proto> file.

Each emitted module reconstructs its file's L<Protobuf::Schema> tree from static
Perl (so the generated code carries B<no> parser or descriptor-set dependency)
and installs every message class through L<Protobuf::Class::Generator> — the exact
same build path the runtime uses. That shared path is what keeps the AOT-emitted
classes and the runtime-generated classes from drifting: there is only one
accessor/codec contract.

Output is B<deterministic>: messages are emitted sorted by full name and the
schema serializer (L<Protobuf::Schema::Serializer>) renders fields in a stable
order, so regenerating an unchanged C<.proto> is byte-identical.

=head1 FUNCTIONS

=head2 package_for

    package_for($proto_package, $prefix)

Maps a dotted protobuf package to a Perl namespace. Every component is
PascalCased; a C<$prefix> (e.g. C<'T::Api'>) replaces that many leading
components.

=head2 perl_class_for

    perl_class_for($message_full_name, $proto_package, $prefix)

Maps a message's fully-qualified name to its generated Perl class name.

=head2 output_path

    output_path($file, $prefix)

The C<.pm> path, relative to the output directory, for a L<Protobuf::Schema::File>.

=head2 render_file

    render_file($schema, $file, $prefix)

Returns the C<.pm> source text for a file.

=head1 LICENSE

This software is licensed under the MIT license. See the C<LICENSE> file.

=cut
